services:
  app:
    build: .
    container_name: sms-procurement-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/smsdb
    networks:
      - smsnet

  db:
    image: postgres:16
    container_name: sms-procurement-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smsnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pardasnikos@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Rene!!@@1122
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - smsnet

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - smsnet

  backup:
    image: postgres:16
    container_name: pgbackup
    restart: always
    environment:
      - PGPASSWORD=postgres
    volumes:
      - postgres_backups:/backups
    depends_on:
      - db
    networks:
      - smsnet
    entrypoint: >
      sh -c '
      echo "‚è∞ Starting scheduled PostgreSQL backups...";
      while true; do
        TS=$(date +%Y-%m-%d_%H-%M);
        pg_dump -h db -U postgres -F c -f /backups/smsdb_$TS.dump smsdb &&
        gzip /backups/smsdb_$TS.dump &&
        find /backups -type f -mtime +7 -delete;
        sleep 86400;
      done
      '

volumes:
  postgres_data:
  portainer_data:
  portainer_certs:
  pgadmin_data:
  postgres_backups:

networks:
  smsnet:
    driver: bridge
